### PR TITLE
build: enable sample generation

### PR DESCRIPTION
**Pull request by ricardosm-cit**
Enable Sample Generator Tool for Data Catalog. See https://github.com/googleapis/nodejs-datacatalog/issues/14 for details.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Cool :) Could I trouble you to try running this with `synthtool`, and to submit those changes along with enabling the flag?

**Comment by ricardosm-cit** [comment]
Hi @JustinBeckwith!
Sure I could submit the changes made by `synthtool` along with enabling the flag. But please let me understand the NodeJS samples generation workflow before doing it.

PTAL at https://github.com/ricardosm-cit/googleapis/pull/2. There you'll see some changes to datacatalog_gapic.yaml and also links to the samples such changes generate to Python (https://github.com/ricardosm-cit/google-cloud-python/pull/2/files) and NodeJS (https://github.com/ricardosm-cit/nodejs-datacatalog/pull/2/files). For Python, the PR in the client library repository is only a reference for reviewers. They will be automatically generated by `samplegen` when called by `synthtool` (the flag has already been enabled in googleapis/google-cloud-python BTW).

Will the workflow for NodeJS be different from this?

**Comment by JustinBeckwith** [comment]
The workflow should be the same - I just want to see what the sample generator is generating before turning it on :) If we just enable the flag here, we wouldn't know what the output looked like until auto-generation runs the following evening, and submits a PR!

**Comment by ricardosm-cit** [comment]
Sure, there are some examples:
https://github.com/ricardosm-cit/nodejs-datacatalog/pull/1/files
https://github.com/ricardosm-cit/nodejs-datacatalog/pull/2/files
https://github.com/ricardosm-cit/nodejs-datacatalog/pull/4/files

**Comment by JustinBeckwith** [comment]
Thanks! Could I trouble you to include those changes on this PR?

**Comment by ricardosm-cit** [comment]
I could include, but I'm not sure if it makes sense because the files will be re-generated once the sample generation has been enabled in this repo. For instance, I didn't submit the generated samples for Python - they only help validating changes to https://github.com/googleapis/googleapis/tree/master/google/cloud/datacatalog/v1beta1/samples before merging them.

Thoughts?

**Comment by bcoe** [comment]
@ricardosm-cit I apologize for this having been left dying on the vine. I agree with Justin that I'd check in both the configuration changes and the generated samples ideally.

Want to update the PR and we'll get this landed?

**Comment by JustinBeckwith** [comment]
We're having this discussion in the speech repository.  Let's get things worked out there first, and then enable it more broadly if we choose to.

**Pull request closed without merging**
