### PR TITLE
feat: add order field to TagField and TagTemplateField

### PR DESCRIPTION
**Pull request by xiaozhenliu-gg5**
1. feat: add `order` field to `TagField` and `TagTemplateField` message in tags.proto
2. fix: broken document links & polish comments
3. chore: update copyright for proto files
4. feat: add csharp/ruby/PHP namespaces

### CODE REVIEW

**Comment by xiaozhenliu-gg5** [comment]
This is waiting for proto change (fixing broken links & proto updates)

**Comment by xiaozhenliu-gg5** [comment]
Sure, modified the title and description details, this would be a new feature for users, but not a breaking change I think. Thank you! @alexander-fenster

**Comment by bcoe** [comment]
@xiaozhenliu-gg5 I would probably merge this calling out the most significant feature being added, which I think would be:

```
feat: add order field to TagField and TagTemplateField
```

**Comment by xiaozhenliu-gg5** [comment]
Thank you @bcoe !

**Pull request merged**
